# Generated by Django 2.2.1 on 2019-07-08 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisualModels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='слоган')),
                ('description', models.TextField(blank=True, verbose_name='подробное описание')),
                ('image', models.ImageField(blank=True, upload_to='visual_images')),
            ],
        ),
    ]
